* Part 1

These caves seem to be lava tubes. Parts are even still volcanically active;
small hydrothermal vents release smoke into the caves that slowly settles like
rain.

If you can model how the smoke flows through the caves, you might be able to
avoid it and be that much safer. The submarine generates a heightmap of the
floor of the nearby caves for you (your puzzle input).

Smoke flows to the lowest point of the area it's in. For example, consider the
following heightmap:

2199943210
3987894921
9856789892
8767896789
9899965678

Each number corresponds to the height of a particular location, where 9 is the
highest and 0 is the lowest a location can be.

Your first goal is to find the low points - the locations that are lower than
any of its adjacent locations. Most locations have four adjacent locations (up,
down, left, and right); locations on the edge or corner of the map have three or
two adjacent locations, respectively. (Diagonal locations do not count as
adjacent.)

In the above example, there are four low points, all highlighted: two are in the
first row (a 1 and a 0), one is in the third row (a 5), and one is in the bottom
row (also a 5). All other locations on the heightmap have some lower adjacent
location, and so are not low points.

The risk level of a low point is 1 plus its height. In the above example, the
risk levels of the low points are 2, 1, 6, and 6. The sum of the risk levels of
all low points in the heightmap is therefore 15.

Find all of the low points on your heightmap. What is the sum of the risk levels
of all low points on your heightmap?

** Ruby

#+name: risk_level
#+begin_src ruby
  def parse_map(lines)
    lines.map { |line| line.strip.split('').map(&:to_i) }
  end

  def adjacent_points(map, row, column)
    points = []
    if row > 0
      points << [row-1, column]
    end

    if column > 0
      points << [row, column-1]
    end

    if row < map.length - 1
      points << [row+1, column]
    end
    if column < map.first.length - 1
      points << [row, column+1]
    end

    points
  end

  def find_low_points(map)
    low_points = []

    map.each_with_index do |line, row|
      line.each_with_index do |height, column|
        if adjacent_points(map, row, column).all? { |i, j| map[i][j] > height }
          low_points << height
        end
      end
    end

    low_points
  end

  def risk_level(low_points)
    low_points.sum + low_points.length
  end
#+end_src

#+begin_src ruby :noweb yes :tangle part1.rb
  <<risk_level>>

  lines = File.readlines('input')

  map = parse_map(lines)
  low_points = find_low_points(map)
  risk_level(low_points)
#+end_src

#+RESULTS:
: 516

* Part 2

Next, you need to find the largest basins so you know what areas are most
important to avoid.

A basin is all locations that eventually flow downward to a single low point.
Therefore, every low point has a basin, although some basins are very small.
Locations of height 9 do not count as being in any basin, and all other
locations will always be part of exactly one basin.

The size of a basin is the number of locations within the basin, including the
low point. The example above has four basins.

The top-left basin, size 3:

2199943210
3987894921
9856789892
8767896789
9899965678

The top-right basin, size 9:

2199943210
3987894921
9856789892
8767896789
9899965678

The middle basin, size 14:

2199943210
3987894921
9856789892
8767896789
9899965678

The bottom-right basin, size 9:

2199943210
3987894921
9856789892
8767896789
9899965678

Find the three largest basins and multiply their sizes together. In the above
example, this is 9 * 14 * 9 = 1134.

What do you get if you multiply together the sizes of the three largest basins?

** Ruby
#+name: calculate_basin_sizes
#+begin_src ruby 
  require 'set'

  def find_low_points(map)
      low_points = []

      map.each_with_index do |line, row|
        line.each_with_index do |height, column|
          if adjacent_points(map, row, column).all? { |i, j| map[i][j] > height }
            low_points << [row, column]
          end
        end
      end

      low_points
    end

    def calculate_basin_sizes(map, low_points)
      low_points.map do |point|
        calculate_basin_size(map, point)
      end
    end


    def calculate_basin_size(map, low_point)
      basin = Set.new([low_point])
      added_points = [low_point]
      while !added_points.empty?
        new_added_points = []
        added_points.each do |point|
          adjacent_points(map, point[0], point[1]).each do |i,j|
            if map[i][j] >= map[point[0]][point[1]] && map[i][j] != 9 && !basin.include?([i,j])
              new_added_points << [i, j]
              basin.add([i,j])
            end
          end
        end
        added_points = new_added_points
      end

      basin.length
    end
#+end_src

#+begin_src ruby :tangle part2.rb :noweb yes 

  <<risk_level>>
  <<calculate_basin_sizes>>

  lines = File.readlines('input')

  map = parse_map(lines)
  low_points = find_low_points(map)
  basin_sizes = calculate_basin_sizes(map, low_points)
  basin_sizes.sort[-3..].reduce(:*)
#+end_src

#+RESULTS:
: 1023660
