#+TITLE: Sonar Sweep

* Part 1
  You're minding your own business on a ship at sea when the overboard alarm
  goes off! You rush to see if you can help. Apparently, one of the Elves
  tripped and accidentally sent the sleigh keys flying into the ocean! Before
  you know it, you're inside a submarine the Elves keep ready for situations
  like this. It's covered in Christmas lights (because of course it is), and it
  even has an experimental antenna that should be able to track the keys if you
  can boost its signal strength high enough; there's a little meter that
  indicates the antenna's signal strength by displaying 0-50 stars. Your
  instincts tell you that in order to save Christmas, you'll need to get all
  fifty stars by December 25th. Collect stars by solving puzzles. Two puzzles
  will be made available on each day in the Advent calendar; the second puzzle
  is unlocked when you complete the first. Each puzzle grants one star. Good
  luck! As the submarine drops below the surface of the ocean, it automatically
  performs a sonar sweep of the nearby sea floor. On a small screen, the sonar
  sweep report (your puzzle input) appears: each line is a measurement of the
  sea floor depth as the sweep looks further and further away from the
  submarine. For example, suppose you had the following report:

  199
  200
  208
  210
  200
  207
  240
  269
  260
  263

  This report indicates that, scanning outward from the submarine, the sonar
  sweep found depths of 199, 200, 208, 210, and so on. The first order of
  business is to figure out how quickly the depth increases, just so you know
  what you're dealing with - you never know if the keys will get carried into
  deeper water by an ocean current or a fish or something. To do this, count the
  number of times a depth measurement increases from the previous measurement.
  (There is no measurement before the first measurement.) In the example above,
  the changes are as follows:

  199 (N/A - no previous measurement)
  200 (increased)
  208 (increased)
  210 (increased)
  200 (decreased)
  207 (increased)
  240 (increased)
  269 (increased)
  260 (decreased)
  263 (increased)
  In this example, there are 7 measurements that are larger than the previous measurement.

  How many measurements are larger than the previous measurement?

** Ruby

#+begin_src ruby :exports both
  increasing_depth_count = 0
  previous_reading = nil
  File.readlines('input').each do |line|
    depth = line.to_i
    if previous_reading && previous_reading < depth
      increasing_depth_count += 1
    end
    previous_reading = depth
  end

  increasing_depth_count
#+end_src

#+RESULTS:
: 1681

** Rust

#+begin_src rust :exports both
  use std::fs::File;
  use std::io::{BufRead, BufReader};

  fn main() {
      let f = File::open("input").expect("Unable to open file");
      let buf = BufReader::new(f);

      let mut increasing_depth_count = 0;
      let mut previous_reading: Option<i32> = None;

      for line in buf.lines() {
          let line = line.expect("Unable to read line");
          let depth = line.parse::<i32>().unwrap();

          if previous_reading.is_some() && previous_reading.unwrap() < depth {
              increasing_depth_count += 1;
          }
          previous_reading = Some(depth);
      }
      println!("{}", increasing_depth_count);
  }
#+end_src

#+RESULTS:
: 1681

* Part 2
  Considering every single measurement isn't as useful as you expected: there's
  just too much noise in the data. Instead, consider sums of a three-measurement
  sliding window. Again considering the above example:

  199  A      
  200  A B    
  208  A B C  
  210    B C D
  200  E   C D
  207  E F   D
  240  E F G  
  269    F G H
  260      G H
  263        H

  Start by comparing the first and second three-measurement windows. The
  measurements in the first window are marked A (199, 200, 208); their sum is
  199 + 200 + 208 = 607. The second window is marked B (200, 208, 210); its sum
  is 618. The sum of measurements in the second window is larger than the sum of
  the first, so this first comparison increased. Your goal now is to count the
  number of times the sum of measurements in this sliding window increases from
  the previous sum. So, compare A with B, then compare B with C, then C with D,
  and so on. Stop when there aren't enough measurements left to create a new
  three-measurement sum. In the above example, the sum of each three-measurement
  window is as follows:

  A: 607 (N/A - no previous sum)
  B: 618 (increased)
  C: 618 (no change)
  D: 617 (decreased)
  E: 647 (increased)
  F: 716 (increased)
  G: 769 (increased)
  H: 792 (increased)

  In this example, there are 5 sums that are larger than the previous sum.
  Consider sums of a three-measurement sliding window. How many sums are larger
  than the previous sum?

** Ruby
#+NAME: initial_solution
#+begin_src ruby :exports both
  increasing_depth_count = 0
  window = []
  previous_window_reading = nil

  File.readlines('input').each do |line|
    depth = line.to_i
    window << depth

    next if window.length < 3

    window_reading = window.sum
    if previous_window_reading && previous_window_reading < window_reading
      increasing_depth_count += 1
    end
    previous_window_reading = window_reading
    window.shift
  end

  increasing_depth_count
#+end_src

#+RESULTS: initial_solution
: 1704

*** Profiling

#+begin_src ruby :noweb yes :results output
  require 'ruby-prof'
  require 'ruby-prof-flamegraph'

  profile = RubyProf.profile do
    1000.times do
      <<initial_solution>>
    end
  end

  printer = RubyProf::GraphHtmlPrinter.new(profile)
  printer.print(File.open('part_2_ruby_profile.html', 'w'))
#+end_src

#+RESULTS:

[[file:./part_2_ruby_profile.html][Result
]]
** Rust

#+begin_src rust :exports both :tangle rust/src/main.rs
  use std::fs::File;
  use std::io::{BufRead, BufReader};

  fn main() {
      let f = File::open("input").expect("Unable to open file");
      let buf = BufReader::new(f);

      let mut increasing_depth_count = 0;
      let mut window = Vec::new();
      let mut previous_window_reading: Option<i32> = None;

      for line in buf.lines() {
          let line = line.expect("Unable to read line");
          let depth = line.parse::<i32>().unwrap();
          window.push(depth);

          if window.len() < 3 {
              continue;
          }

          let window_reading: i32 = window.iter().sum();
          if previous_window_reading.is_some() && previous_window_reading.unwrap() < window_reading {
              increasing_depth_count += 1;
          }
          previous_window_reading = Some(window_reading);
          window.remove(0);
      }
      println!("{}", increasing_depth_count);
  }
#+end_src

#+RESULTS:
: 1704

*** Profiling

#+begin_src bash
  cd rust
  cargo flamegraph --dev
#+end_src

[[file:./rust/flamegraph.svg][Flame Graph]]
