* Part 1

The incredible pressures at this depth are starting to put a strain on your
submarine. The submarine has polymerization equipment that would produce
suitable materials to reinforce the submarine, and the nearby
volcanically-active caves should even have the necessary input elements in
sufficient quantities.

The submarine manual contains instructions for finding the optimal polymer
formula; specifically, it offers a polymer template and a list of pair insertion
rules (your puzzle input). You just need to work out what polymer would result
after repeating the pair insertion process a few times.

For example:

NNCB

CH -> B
HH -> N
CB -> H
NH -> C
HB -> C
HC -> B
HN -> C
NN -> C
BH -> H
NC -> B
NB -> B
BN -> B
BB -> N
BC -> B
CC -> N
CN -> C

The first line is the polymer template - this is the starting point of the
process.

The following section defines the pair insertion rules. A rule like AB -> C
means that when elements A and B are immediately adjacent, element C should be
inserted between them. These insertions all happen simultaneously.

So, starting with the polymer template NNCB, the first step simultaneously
considers all three pairs:

The first pair (NN) matches the rule NN -> C, so element C is inserted between
the first N and the second N.

The second pair (NC) matches the rule NC -> B, so
element B is inserted between the N and the C.

The third pair (CB) matches the
rule CB -> H, so element H is inserted between the C and the B.

Note that these pairs overlap: the second element of one pair is the first
element of the next pair. Also, because all pairs are considered simultaneously,
inserted elements are not considered to be part of a pair until the next step.

After the first step of this process, the polymer becomes NCNBCHB.

Here are the results of a few steps using the above rules:

Template:     NNCB
After step 1: NCNBCHB
After step 2: NBCCNBBBCBHCB
After step 3: NBBBCNCCNBBNBNBBCHBHHBCHB
After step 4: NBBNBNBBCCNBCNCCNBBNBBNBBBNBBNBBCBHCBHHNHCBBCBHCB

This polymer grows quickly. After step 5, it has length 97; After step 10, it
has length 3073. After step 10, B occurs 1749 times, C occurs 298 times, H
occurs 161 times, and N occurs 865 times; taking the quantity of the most common
element (B, 1749) and subtracting the quantity of the least common element
(H, 161) produces 1749 - 161 = 1588.

Apply 10 steps of pair insertion to the polymer template and find the most and
least common elements in the result. What do you get if you take the quantity of
the most common element and subtract the quantity of the least common element?

** Ruby

#+name: expand_sequence
#+begin_src ruby
  def parse_rules(lines)
    rules = {}
    lines.each do |line|
      if /(?<pair>[A-Z]{2}) -> (?<inserted>[A-Z])/ =~ line
        rules[pair] = [pair[0], inserted, pair[1]]
      end
    end
    rules
  end

  def expand_rules(rules, original_rules)
    new_rules = {}
    rules.each do |pair, output|
      new_output = []
      output.each_with_index do |c, i|
        if i+1 == output.length
          new_output << c
          break
        end

        if pair_output = original_rules[c+output[i+1]]
          new_output += pair_output[...-1]
        else
          new_output << c
        end
      end
      new_rules[pair] = new_output
    end

    new_rules
  end

def expand_sequence(sequence, rules)
  new_sequence = []
  sequence.each_char.with_index do |c, i|
    if i+1 == sequence.length
      new_sequence << c
      break
    end
    if sub = rules[c+sequence[i+1]]
      new_sequence += sub[...-1]
    else
      new_sequence << c
    end
  end
  new_sequence.join
end
#+end_src

#+name: score
#+begin_src ruby
  def score(sequence)
    frequencies = sequence.each_char.to_a.tally
    frequencies.values.max - frequencies.values.min
  end
#+end_src

#+begin_src ruby :noweb yes :tangle part1.rb
  <<expand_sequence>>
  <<score>>

  lines = File.readlines('input')
  rules = parse_rules(lines)
  original_rules = rules.dup
  9.times do
    rules = expand_rules(rules, original_rules)
 end
 score(expand_sequence(lines[0].strip, rules))
#+end_src

#+RESULTS:
: 3906

* Part 2

The resulting polymer isn't nearly strong enough to reinforce the submarine.
You'll need to run more steps of the pair insertion process; a total of 40 steps
should do it.

In the above example, the most common element is B (occurring 2192039569602
times) and the least common element is H (occurring 3849876073 times);
subtracting these produces 2188189693529.

Apply 40 steps of pair insertion to the polymer template and find the most and
least common elements in the result. What do you get if you take the quantity of
the most common element and subtract the quantity of the least common element?

** Ruby
#+name: expand_pairs
#+begin_src ruby
def parse_rules(lines)
  rules = {}
  lines.each do |line|
    if /(?<pair>[A-Z]{2}) -> (?<inserted>[A-Z])/ =~ line
      rules[pair] = [pair[0]+inserted, inserted+pair[1]]
    end
  end
  rules
end

def count_pairs(sequence)
  sequence.each_char.to_a.each_cons(2).reduce({}) do |counts, pair|
    counts[pair.join] ||= 0
    counts[pair.join] += 1
    counts
  end
end

def expand_pairs(pairs, rules)
  new_counts = {}
  pairs.each do |pair, count|
    rules[pair].each do |new_pair|
      new_counts[new_pair] ||= 0
      new_counts[new_pair] += count
    end
  end
  new_counts
end

def score(pairs, sequence)
  frequencies = {}
  pairs.each do |pair, count|
    frequencies[pair[0]] ||= 0
    frequencies[pair[0]] += count
  end
  frequencies[sequence[-1]] += 1
  frequencies.values.max - frequencies.values.min
end
#+end_src

#+begin_src ruby :noweb yes :tangle part2.rb
   <<expand_pairs>>

   lines = File.readlines('input')
   rules = parse_rules(lines)
   sequence = lines[0].strip
   pairs = count_pairs(sequence)
   40.times do
     pairs = expand_pairs(pairs, rules)
   end
  score(pairs, sequence)
#+end_src

#+RESULTS:
: 4441317262452

